import type { Metadata } from "next";
import Link from "next/link";
import { KoveLogo } from "@/components/KoveLogo";

export const metadata: Metadata = { title: "Terms of Service — Kove" };

const EFFECTIVE = "June 25, 2025";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-300">
      <nav className="border-b border-white/[0.06] h-14 flex items-center px-6">
        <div className="mx-auto w-full max-w-3xl flex items-center justify-between">
          <Link href="/">
            <KoveLogo className="h-6 w-auto" />
          </Link>
          <Link href="/privacy" className="text-sm text-zinc-500 hover:text-white transition-colors">
            Privacy Policy
          </Link>
        </div>
      </nav>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-3xl font-semibold text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-zinc-500 mb-12">Effective date: {EFFECTIVE}</p>

        <div className="space-y-10 text-sm leading-7">

          <section>
            <h2 className="text-base font-semibold text-white mb-3">1. Acceptance</h2>
            <p>
              By accessing or using Kove ("Service"), operated by Kove Labs ("we", "us"), you agree to
              these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              Kove is a SaaS platform that helps startup founders conduct AI-powered market research,
              including competitive analysis, user pain point identification, and product opportunity
              discovery. The Service pulls data from public sources (app stores, review platforms, public
              web content) and uses AI to synthesize reports.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">3. Accounts</h2>
            <p>
              You must create an account to use the Service. You are responsible for maintaining the
              confidentiality of your credentials and for all activity under your account. You must
              provide accurate information and notify us immediately of any unauthorized use at{" "}
              <a href="mailto:hello@trykove.dev" className="text-white underline underline-offset-2">
                hello@trykove.dev
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc list-inside space-y-1 text-zinc-400 pl-2">
              <li>Use the Service for any unlawful purpose</li>
              <li>Resell, sublicense, or redistribute Service output without our written consent</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the platform infrastructure</li>
              <li>Use the Service to generate content that infringes third-party intellectual property</li>
              <li>Circumvent usage limits or billing controls</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">5. Subscriptions &amp; Billing</h2>
            <p>
              Paid plans are billed in advance on a monthly or annual basis. All fees are non-refundable
              except where required by law or at our sole discretion. We reserve the right to change
              pricing with 30 days' notice. Failure to pay may result in suspension or termination of
              your account.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">6. AI-Generated Content</h2>
            <p>
              Reports and analysis generated by the Service are produced by AI and are for informational
              purposes only. They do not constitute professional business, legal, or financial advice.
              We make no guarantee as to the accuracy, completeness, or fitness for any particular
              purpose of AI-generated output. You use the output at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">7. Intellectual Property</h2>
            <p>
              The Service and its underlying technology remain our exclusive property. You retain
              ownership of any original content you submit. By using the Service, you grant us a
              limited license to process your inputs solely to provide the Service. We do not use
              your workspace data to train AI models.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">8. Third-Party Data</h2>
            <p>
              The Service accesses publicly available data from third-party platforms (Apple App Store,
              Google Play, Reddit, and others). We are not affiliated with these platforms and cannot
              guarantee the accuracy or availability of their data. Use of data sourced from third
              parties is subject to those platforms' terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">9. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" and "as available" without warranties of any kind, express
              or implied, including but not limited to merchantability, fitness for a particular purpose,
              or non-infringement. We do not warrant that the Service will be uninterrupted or error-free.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">10. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Kove Labs shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages arising from your use of the
              Service. Our total liability to you shall not exceed the amount you paid us in the
              twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">11. Termination</h2>
            <p>
              We may suspend or terminate your access at any time for violation of these Terms or for
              any other reason at our discretion, with or without notice. You may cancel your account
              at any time from the Settings page. Upon termination, your data may be deleted after
              30 days.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">12. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify you of material changes via
              email or in-app notice. Continued use of the Service after changes take effect constitutes
              acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">13. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Delaware, without regard to conflict
              of law principles. Any disputes shall be resolved in the courts of Delaware.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-white mb-3">14. Contact</h2>
            <p>
              Questions about these Terms?{" "}
              <a href="mailto:hello@trykove.dev" className="text-white underline underline-offset-2">
                hello@trykove.dev
              </a>
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-white/[0.06] mt-16 py-8 text-center text-xs text-zinc-600">
        <div className="flex items-center justify-center gap-4">
          <span>© {new Date().getFullYear()} Kove Labs</span>
          <Link href="/privacy" className="hover:text-zinc-400 transition-colors">Privacy Policy</Link>
          <Link href="/terms" className="hover:text-zinc-400 transition-colors">Terms of Service</Link>
        </div>
      </footer>
    </div>
  );
}
