export const APPS = [
  {
    id: "turbo",
    name: "Turbo AI",
    color: "#8b5cf6",
    rating: 4.3,
    reviews: 8200,
    downloadsLabel: "42K / mo",
    revenueLabel: "$85K / mo",
    pricing: "$7.99 / mo",
    platforms: ["iOS", "Android"],
    description: "AI-first notes with voice transcription",
    strengths: ["Voice transcription", "AI summarization"],
    weaknesses: ["No web clipper", "Weak collaboration"],
    topPain: "No web clipper on mobile",
    topPainSignal: 4,
  },
  {
    id: "studley",
    name: "Studley",
    color: "#3b82f6",
    rating: 4.6,
    reviews: 14500,
    downloadsLabel: "28K / mo",
    revenueLabel: "$52K / mo",
    pricing: "Free + $9.99 / mo",
    platforms: ["iOS"],
    description: "Study-focused AI notes for students",
    strengths: ["Flashcard generation", "Study mode"],
    weaknesses: ["Sync unreliable", "iOS only"],
    topPain: "Sync fails across devices",
    topPainSignal: 4,
  },
  {
    id: "coconote",
    name: "Coconote",
    color: "#10b981",
    rating: 4.1,
    reviews: 3400,
    downloadsLabel: "15K / mo",
    revenueLabel: "$18K / mo",
    pricing: "$4.99 / mo",
    platforms: ["iOS", "Android"],
    description: "Collaborative real-time AI notes",
    strengths: ["Real-time collaboration", "Affordable"],
    weaknesses: ["No PDF export", "Limited AI depth"],
    topPain: "Can't export to PDF",
    topPainSignal: 3,
  },
  {
    id: "notee",
    name: "Notee",
    color: "#f59e0b",
    rating: 3.8,
    reviews: 1200,
    downloadsLabel: "9K / mo",
    revenueLabel: "$7K / mo",
    pricing: "Free",
    platforms: ["iOS", "Android"],
    description: "Simple AI note organizer",
    strengths: ["Completely free", "Simple UX"],
    weaknesses: ["Generic AI responses", "No power features"],
    topPain: "AI responses feel generic",
    topPainSignal: 3,
  },
] as const;

export const PAIN_POINTS = [
  { rank: 1, text: "No reliable offline mode", signal: 4, apps: ["Turbo AI", "Studley", "Coconote"] },
  { rank: 2, text: "Sync fails across devices", signal: 4, apps: ["Studley", "Notee"] },
  { rank: 3, text: "Can't export to PDF or Markdown", signal: 3, apps: ["Coconote"] },
  { rank: 4, text: "AI summaries feel templated", signal: 3, apps: ["Turbo AI", "Notee"] },
  { rank: 5, text: "No web clipper on mobile", signal: 4, apps: ["Turbo AI"] },
] as const;

export const MARKET_GAP = {
  title: "Offline-first notes with reliable sync and one-tap PDF export",
  opportunity:
    "No player reliably handles offline sync AND PDF/Markdown export. Turbo AI, Studley, and Coconote users all flag the exact same friction — a focused app that nails both flows is a clear wedge into this market.",
  confirmedBy: 3,
} as const;
