"use client";

import { useState } from "react";
import { Download, Copy, FileText, Check } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
  DropdownMenuLabel,
} from "@/components/ui/dropdown-menu";
import { useBilling } from "@/hooks/useBilling";
import { PaywallModal } from "@/components/paywall/PaywallModal";
import { UpgradeChip } from "@/components/paywall/UpgradeChip";
import type { NodeReport } from "../../../mockData";

interface Props {
  appName: string;
  report: NodeReport;
}

function fmtNum(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${Math.round(n / 1_000)}K`;
  return n.toString();
}

function buildMarkdown(appName: string, report: NodeReport): string {
  const lines: string[] = [];

  lines.push(`# ${appName} — Competitor Intelligence Report`);
  lines.push(`_Generated by One1_\n`);

  // Key metrics
  const est = report.estimate;
  if (est) {
    lines.push(`## Market Data`);
    if (est.downloads !== null) lines.push(`- **Downloads/mo:** ${fmtNum(est.downloads)}`);
    if (est.revenue !== null) lines.push(`- **Revenue/mo:** $${fmtNum(est.revenue)}`);
    lines.push("");
  }

  if (report.rating) {
    lines.push(`## Rating`);
    lines.push(`★ ${report.rating.toFixed(1)} (${report.reviewCount?.toLocaleString() ?? "—"} reviews)\n`);
  }

  // Pricing
  if (report.pricingModel) {
    lines.push(`## Pricing`);
    lines.push(`**Model:** ${report.pricingModel}\n`);
    if (report.pricingTiers?.length) {
      for (const tier of report.pricingTiers) {
        lines.push(`### ${tier.name} — ${tier.price} (${tier.period})`);
        if (tier.features?.length) {
          for (const f of tier.features) lines.push(`- ${f}`);
        }
        lines.push("");
      }
    }
  }

  // Pain points
  if (report.painPoints?.length) {
    lines.push(`## Pain Points`);
    for (const pp of report.painPoints) {
      lines.push(`### [${pp.severity}] ${pp.title}`);
      if (pp.quote) lines.push(`> "${pp.quote}"`);
      lines.push("");
    }
  }

  // Positive signals
  if (report.positiveSignals?.length) {
    lines.push(`## Positive Signals`);
    for (const s of report.positiveSignals) {
      lines.push(`### ${s.theme}`);
      lines.push(`_${s.frequency}_`);
      if (s.quote) lines.push(`> "${s.quote}"`);
      lines.push("");
    }
  }

  // AI synthesis
  if (report.aiSynthesis) {
    lines.push(`## AI Analysis`);
    if (report.aiSynthesis.doesWell) {
      lines.push(`**Does well:** ${report.aiSynthesis.doesWell}\n`);
    }
    if (report.aiSynthesis.fails) {
      lines.push(`**Fails at:** ${report.aiSynthesis.fails}\n`);
    }
    if (report.aiSynthesis.implication) {
      lines.push(`**Implication:** ${report.aiSynthesis.implication}\n`);
    }
  }


  return lines.join("\n");
}

export function ExportButton({ appName, report }: Props) {
  const billing = useBilling();
  const [copied, setCopied] = useState(false);
  const [paywallOpen, setPaywallOpen] = useState(false);

  async function copyMarkdown() {
    const md = buildMarkdown(appName, report);
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function downloadMarkdown() {
    const md = buildMarkdown(appName, report);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${appName.toLowerCase().replace(/\s+/g, "-")}-report.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function printPdf() {
    window.print();
  }

  if (!billing.loading && !billing.isPro) {
    return (
      <>
        <button
          onClick={() => setPaywallOpen(true)}
          className="flex items-center gap-1.5 rounded-lg border border-white/[0.08] bg-zinc-900 px-3 py-2 text-xs font-medium text-zinc-400 transition-colors hover:border-white/[0.16] hover:text-white"
        >
          <Download className="h-3.5 w-3.5" />
          Export
          <UpgradeChip />
        </button>
        <PaywallModal
          open={paywallOpen}
          onClose={() => setPaywallOpen(false)}
          gate="export"
        />
      </>
    );
  }

  return (
    <>
    <DropdownMenu>
      <DropdownMenuTrigger className="flex items-center gap-1.5 rounded-lg border border-white/[0.08] bg-zinc-900 px-3 py-2 text-xs font-medium text-zinc-400 transition-colors hover:border-white/[0.16] hover:text-white outline-none">
        <Download className="h-3.5 w-3.5" />
        Export
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-44">
        <DropdownMenuLabel className="text-[10px] font-semibold tracking-widest text-zinc-600 uppercase">
          Export as
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem
          className="flex cursor-pointer items-center gap-2"
          onClick={copyMarkdown}
        >
          {copied ? (
            <Check className="h-3.5 w-3.5 text-[#2dd4bf]" />
          ) : (
            <Copy className="h-3.5 w-3.5" />
          )}
          {copied ? "Copied!" : "Copy Markdown"}
        </DropdownMenuItem>
        <DropdownMenuItem
          className="flex cursor-pointer items-center gap-2"
          onClick={downloadMarkdown}
        >
          <FileText className="h-3.5 w-3.5" />
          Download .md
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem
          className="flex cursor-pointer items-center gap-2"
          onClick={printPdf}
        >
          <Download className="h-3.5 w-3.5" />
          Save as PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
    </>
  );
}
